spring:

  datasource:
    url: jdbc:mysql://localhost:3306/livsi
    username: root
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

aws:
  s3:
    bucket: S3 버킷 이름
  credentials:
    accessKey: aws IAM 사용자에서 키 생성해서 나오는 ID
    secretKey: " 시크릿 ID
  region:
    static: ap-northeast-2