spring:

  datasource:
    url: jdbc:mysql://localhost:3306/livsi
    username: root
    password: "0409"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

aws:
  s3:
    bucket: minseotest0409
  credentials:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region:
    static: ap-northeast-2