spring:
  application:
    name: VideoAnalyze2
  servlet:
    multipart:
      # 업로드 파일 크기 설정
      max-file-size: 50MB
      max-request-size: 50MB

gemini:
  requestText: |
    "해당 영상을 짜깁기 해서 맛집 홍보 쇼츠 영상을 만들려고 해 영상 시나리오를 만들어줘
    총 30초 정도의 영상 분량이 나오게 해줘
    1) JSON 형식으로 응답해줘
    <출력 예시> {"concept": "죽이 아플 때만 먹는 음식이라고? 편견을 깨부수는 세상의 모든 죽이 여기에!", "scenes":[{"sceneNumber":1, "originalTimestamp":"0:15-0:20", "content": "이런 죽 본 적 있어?"},{"sceneNumber": 2,"originalTimestamp":"0:08-0:13","content": "속 편한 보양죽부터 든든한 식사죽까지"},{sceneNumber": 3, "originalTimestamp": "0:05-0:10", "content": "정기운 백련죽집"}, {"sceneNumber": 4,"originalTimestamp": "0:13-0:18", "content": "달콤한 전통죽과 수제 디저트는 기본!"}, {"sceneNumber": 5, "originalTimestamp": "0:12-0:17", "content": "아니, 떡볶이랑 크로와상까지?"}, {"sceneNumber": 6,"originalTimestamp": "0:15-0:20", "content": "죽의 신세계가 궁금하다면? 정기운 백련죽집으로!"}]}
    2) "originalTimestamp":"a-b"라 하면 b가 무조건 존재하게 해줘


  key: AIzaSyAzGqHSTpzr_MhZzdHEqkZDOgzzcahUSPU


google:
  cloud:
    key: ${GOOGLE_APPLICATION_CREDENTIALS}


